### ISSUE TITLE
Remove jQuery dependency from tests?

### ISSUE THREAD

**Issue by ghost** [ngOfficeUIFabric/ng-officeuifabric#106]
jQuery is loaded with the unit tests, to make DOM manipulation easier. However, when a directive depends on jQuery (which they should not), this error is not detected by the unit test. This has already caused issues like [this one](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/98).

I think we should remove jQuery from the test runners, except if there is a better solution.

**Comment by s-KaiNet** [comment]
This can be problematic, because we are using `jasmine-jquery` (which, in turn relies on jquery, correct me if I'm wrong) for convenient things like `toBeInDOM`, `toHaveClass` etc.  
Without this writing tests and assertions, in particular, becomes harder.

**Comment by andrewconnell** [comment]
I've got feelings on both sides of this... since a lot of our tests need to check for the existence of stuff in the DOM & presence of CSS classes, this comes in quite handy. What's the alternative? Maybe someone can research how Material does it?

**Comment by andrewconnell** [comment]
Thinking more about this, I agree with @rolandoldengarm ... this should be removed. Otherwise we could have false positives when running our tests. Yes, this will make tests more complicated as @s-KaiNet mentions above.

Warrants further investigation how Angular Material handles this... maybe it means we need a test library to help us if someone hasn't already done this...

**Comment by s-KaiNet** [comment]
What we need to do is just push `angular.js` inclusion in the page above `jasmine-jquery.js`. In that way angular will think that there is no jquery, but tests can be written with help of `jasmine-jquery`. But how to do this? According karma config, `files` always inlcuded after `frameworks` on the page.   

One option which I'm thinking about is to drop `jasmine-jquery` from karma config and load it dynamically right in .spec.ts files (create base class or something, so other specs can inherit this). But it looks like overhead. I believe there should be a simpler solution.

**Comment by jjczopek** [comment]
In general I'm supportive of the idea as I have run into some trouble based on that. However the trade-off of loosing all the help and helpers is big.

If we were to drop jQuery from unit tests, in order to keep writing tests efficiently, we probably should come up with some helpers as substitute for the lost jQuery helpers. Question is whether we want to put effort into that  and when should that be.

**Comment by andrewconnell** [comment]
IMHO we need to do this sooner rather than later. We aren't half-way through implementing the directives so now is the best time.

I don't see the Angular Material guys using `jasmine-jquery`... so we should be able to do this. Curious how bad of an impact this will be when removing this framework...

**Comment by andrewconnell** [comment]
Ouch... just removed `jasmine-jquery` and ran the tests... 67 of 80 tests _failed_ ...

**Comment by s-KaiNet** [comment]
I believe something following should work (don't have time to test right now):  
under `config/karma.ts` remove `jasmine-jquery` from `frameworks`, then under `files` add `jquery.js` and `jasmine-jquery.js` after `angular.js`  
In `.spec` files you need something like this:   

``` javascript
element = ng.element('<uif-icon uif-type="arrowDownLeft" />');
....$compile(element)(scope);
.......
element = jQuery(element[0]);
```

**Comment by andrewconnell** [comment]
If this worked, that would be ideal because then we don’t have to change anything in the tests… they would all keep working… just a config tweak.

What would be a great test (adding to my backlog) is to (1) jump back to the commit –1 that fixed a bug in the dropdown that was impacted by jQuery vs sqlite (https://github.com/ngOfficeUIFabric/ng-officeuifabric/commit/a24e51dd5663f612616566f3850540f3b0341810), (2) run all tests (that should pass), then (3) make this change you suggest & then run tests (that should fail) and then (4) apply the changes in the above commit & rerun the tests (that should pass).

If all that works as expected, we could apply it in the next release.

**Comment by s-KaiNet** [comment]
So I tested this and here is the results:  
I didn't revert to commit, but made it in a slightly different way. I removed all directives except dropdown, add folowing spec: 

``` javascript
 it('should be jQuery instance', inject(($compile: Function, $rootScope: ng.IRootScopeService) => {
    let $scope: any = $rootScope.$new();
    let dropdown: JQuery = $compile('<fun!:)>')($scope);
    expect(dropdown instanceof jQuery).toBe(false);
    dropdown = jQuery(dropdown[0]);
    expect(dropdown instanceof jQuery).toBe(true);
}));
```

When runing `gulp test` it fails because `expect(dropdown instanceof jQuery).toBe(false);` is true (jQuery included before angular in tests).  
Then I created another karma config - `karma.jqueryless.ts`, created option to run this config - `gulp test --jq`. `karma.jqueryless.ts` contains all changes I mentioned previously - removed `jasmine-jquery` and added it udner `files`. And test is green, because in that case angular think that there is no jQuery and `$compile` return JQLite (this can be proven in debug mode in chrome), so first check is correct. Second check is also OK because now dropdown is wrapped in jQuery.  
Looks good, but as always drawbacks:  
**Issue 1** - you need to update all tests and wrap `$element` with jQuery for convenient selection, `toHaveClass`, etc.

**Issue 2** - the most strange. `click()` event not working correctly when testing with `Phantomjs`. When browser is Chrome - all tests are good, in `Phantomjs` not. I saw this before on my own way with Phantomjs and found workaround [here](http://stackoverflow.com/questions/15739263/phantomjs-click-an-element#answer-15948355). With this function `Phantomjs` also works just fine. I pushed my branch here - [issue-jqlite](https://github.com/s-KaiNet/ng-officeuifabric/tree/issue-jqlite) you can grab it and take a look (points of interest - `karma.jqueryless.ts`, `dropdownDirective.spec.ts`). Run `gulp test --jq` - tests are green. Comment lines 101-102, uncomment 99-100 under `dropdownDirective.ts` - tests are red. 

As a result this approach works with its issues. IMHO we have two options: 1. Drop `Phantomjs` and use `Chrome` for testing. 2. Leave `Phantomjs`, but this require a bit of additional work.

**Comment by andrewconnell** [comment]
Nice work... I'll take a look. I like being able to use this, but I think when we see PR's submitted, we have to do a code review to ensure they aren't missing this fundamental thing... or just put it in the guidelines.

**Comment by andrewconnell** [comment]
I've tried your steps when i forked your repo but regardless of which one (commenting 99-100 / 101-102) I see 6 failing tests.

I _really_ don't want to move to Chrome... we can't get rid of Phantom because it kills our TravisCI tests.

**Comment by s-KaiNet** [comment]
Did you run `gulp test --jq`?  
Also please make sure to run `npm install`

**Comment by andrewconnell** [comment]
Yup... clean clone, `npm install` and `gulp test --jq`... I'll give it another shot when I get home (slow connection where I am so npm install will take a while).

**Comment by s-KaiNet** [comment]
Yep... this is my bad.. forgot to add jquery as deps (in my node_modules it was for some reason).  
Pushed fixed `package.json`. To be clear: 

``` bash
git clone https://github.com/s-KaiNet/ng-officeuifabric.git ngfabric-jqlite
cd ngfabric-jqlite
git checkout issue-jqlite
npm install
tsc -p ./
gulp test --jq

```

Should be green this time :)

**Comment by andrewconnell** [comment]
OK, that fixed it… I think this is perfectly fine to require the things you’ve listed for the requirements & workaround for PhantomJS.

Do you want to update the guideline doc adding some information about it with the samples (make sure to reference this issue within the guideline so people can see a history) & submit a PR? Then we should likely create issues for each directive that needs to be updated.

**Comment by s-KaiNet** [comment]
I added one more script for karma config which fix `click` problem in `Phantomjs`, pushed that commit in my branch. The file is under `build/jquery.phantomjs.fix.js` (hmm not sure where to put this, `build` folder not looks like good one, but no other options). This file included under `karma.jqueryless.ts` in `files` section. In this way no need to worry about fixing `Phantnomjs` in every spec, fix will be loaded automatically. Added contextual menu to see how hard it will be apply jQuery to make build green, and it appears that no so much efforts, just:   

``` javascript
let $element: JQuery;
....
$element = jQuery($element[0]);
```

in every `beforeeach`.   

**From the other side**, looking into ngMaterial, they are not using jquery in tests at all. Pure jqLite, `getElementById`, `querySelector`. Events get triggered by `triggerHandler` (jqLite) and all this works just fine...  
So the question is, should we use this `dance` with `jquery`, `jasmine-jquery` and `Phantomjs` fixing or just burn all this in favor of jqLite and vanillajs?   

```
switch (question):
    case 'option #1': 

in that case I'm ready to update docs and fix all existing tests 
(it seems fixes are simple, and as I already digged into this, I can do that quicker)

   case 'option #2': 

burn `jQuery`, everybody need to fix own tests, because they are probably won't work.
```

PS: for me `option #1` looks a bit better, because jquery and this `phantomjs` fix doesn't ruin everything, it's just an option for quicker test development, if you don't want, you can use `option #2` without problems.

**Comment by ghost** [comment]
Great work @s-KaiNet !
I'm more leaning towards option 2. option 1 has a couple of 'hacks' and fixes that may work now, but may cause issues longer down the road. In most of the projects where we implemented hacks in any form things started acting weird.

As we want to mimic Angular Material, I think option 2 is the way to go.

**Comment by andrewconnell** [comment]
Let me ask this... @s-KaiNet the way I understand your option 1, if we change the karma config which avoid any false positives in tests where the directive takes a dependency on jQuery. If they want to use jQuery via jasmine-jquery in their tests, they have to do this little extra work that you've documented. Is that correct? 

**If so, then I'd say we let developers do either one.**

However, if option 1 requires developers write their tests in a specific way to make sure they don't get false positives & thus, introduces a code review by someone when a PR is submitted to ensure that they aren't using jQuery in the directive, then I'd be more in favor of option 2.

While my default stance has been what @rolandoldengarm mentions (to mimic Angular Material), I'm also in favor of not putting too many requirements on contributors. My position is more that we default to Angular Material.

**Comment by andrewconnell** [comment]
BTW, I'd put that `*.js` file in the `src/core/` folder. It's a testing resource and since it won't get referenced in any of the directives, webpack won't suck it into the bundle.

**Comment by s-KaiNet** [comment]
@andrewconnell you are correct in your understanding `#1`.  
In any case we are removing jQuery from angular, because it generates false positives in tests. The question is actually: should we allow to use jQuery in tests through this "hacks" or not.  
I'm also agree with @rolandoldengarm and have some doubts.

**Comment by andrewconnell** [comment]
Then my answer is option 3 – we modify our karma config to make sure we don’t load jQuery when testing. Then we leave developers the option to test without jasmine-query OR they can but need to use a little hackery to use it, and we provide guidance.

IMHO, we should have a new section within the testing doc that explains what’s going on and shows how to leverage the hack you did.

Nice work!

**Comment by s-KaiNet** [comment]
So our next steps:  
in `karma.config` drop `jasmine-jquery` from `frameworks` section, add `jquery`, `jasmine-jquery` and "workaround" script under `files` section. Update docs accordingly.  
After merging most of the tests will fail. Every developer need to fix that using jqLite+vanillajs OR use "hacky" approach.  
Is that correct?

**Comment by andrewconnell** [comment]
LGTM... what we'll do is when you submit this PR, we'll have a separate branch that will address this change that people can fix which will ultimately get merged into `dev`

**Comment by jjczopek** [comment]
Looks good. I personally will go with "hacky" because I think tests look a bit cleaner with jasmine-jquery, and migration effort will be smaller than doing it jqLite/vanilla way.

**Comment by s-KaiNet** [comment]
@andrewconnell  Can you please create those branch? I guess when submitting the PR I need to target this branch and not dev. Am I correct?

**Comment by andrewconnell** [comment]
Nah… go ahead & submit it to DEV… I’m doing all PR merging locally and pushing to the repo to make sure things don’t get screwed up along the way to keep the repo as clean as possible. If you can, just make it clear in the description of the PR what this is. When I push it up, I’ll push it in a new branch.

More info:
The way I do it locally which you can see in the MERGE-REQUEST doc is create a new branch locally off origin/dev & pull the PR into it. When everything is done & looks good, I switch back to dev and rebase it on the PR branch. I’ll just skip that last step and push the new branch straight to the repo.
