### ISSUE TITLE
live-dev throws outofmemory exception after a while

### ISSUE THREAD

**Issue by ghost** [ngOfficeUIFabric/ng-officeuifabric#160]
After a while (e.g. 10-20 test runs), live-dev throws an out of memory exception:

```
<--- Last few GCs --->                                                                                                                                     

 1640293 ms: Mark-sweep 1387.3 (1455.9) -> 1386.6 (1455.9) MB, 2093.8 / 0 ms [allocation failure] [GC in old space requested].                             
 1642915 ms: Mark-sweep 1386.6 (1455.9) -> 1386.6 (1455.9) MB, 2622.0 / 0 ms [allocation failure] [GC in old space requested].                             
 1644813 ms: Mark-sweep 1386.6 (1455.9) -> 1386.6 (1455.9) MB, 1898.7 / 0 ms [last resort gc].                                                             
 1646753 ms: Mark-sweep 1386.6 (1455.9) -> 1386.3 (1455.9) MB, 1939.9 / 0 ms [last resort gc].                                                             


<--- JS stacktrace --->                                                                                                                                    

==== JS stack trace =========================================                                                                                              

Security context: 00000136BC4B4639 <JS Object>                                                                                                             
    2: emitJavaScriptWorker(aka emitJavaScriptWorker) [C:\Projects\ng-officeuifabric\node_modules\gulp-typescript\node_modules\typescript\lib\typescript.js
5605] [pc=000001F6B00FB2D6] (this=00000136BC4041B9 <undefined>,node=0000009CDA4C73B9 <a Node with map 00000144514A72C1>)                                   
    3: emitNodeWithoutSourceMap(aka emitNodeWithoutSourceMap) [C:\Projects\ng-officeuifabric\node_modules\gulp-types...                                    

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory      
```

**Comment by andrewconnell** [comment]
:+1: I see the same thing

**Comment by s-KaiNet** [comment]
I will take a look on this today's evening (currently don't have time, my regular work.... oh.. :) ).  
_disgusting error..._

**Comment by s-KaiNet** [comment]
Made a few tests - created a very basic watcher - just `gulp.watch(['./**/*.ts'], ['build-lib']);`. After 20-30 iterations fails with out of memory...omg... that's not good.  
The problem can be in 1) webpack 2) web pack ts-loader 3) typescript compiler

**Comment by s-KaiNet** [comment]
So I've tried different options - `gulp.watch(['./**/*.ts'], ['build-lib']);`, `gulp.watch(['./**/*.ts'], ['test']);`, `gulp.watch(['./**/*.ts'], ['transpile-ts']);`. Only in case of `transpile-ts` there are **NO** OOM exceptions.  
For me it looks like the problem is in webpack, because `test` is  also using webpack.  
Also I found following threads - [this one](https://github.com/webpack/webpack/issues/1914) and [this](https://github.com/webpack/webpack/issues/1875), tried suggested workaround and run `node --max_old_space_size=4096 c:\Projects\ng-officeuifabric\node_modules\gulp\bin\gulp.js live-dev` - same OOM exception but only when you exceed 4GB. The only difference that you have 40-50 shots in that case.  
From my view we can following options:
- leave it as is - you have 10-20 shots - not bad, huh
- use workaround with `--max_old_space_size=4096` and you get 40-50 shots - that's better, but requires a lot of free memory
- use spawn-process - run `build-lib` and `test` in separate node process which will be closed immediately after finishing, increase complexity, require more coding and required some kind of POC
- your own option here 

For me the first and the second options are bad and actually not options at all. 
Looking for your opinions, comments, suggestions, thoughts, @ngOfficeUIFabric/ngofficeuifabric-members

**Comment by andrewconnell** [comment]
Man that really sucks… we are currently running a slightly older (by 2+ months) version of webpack (1.12.9)… Wonder if latest (1.12.12) has any impact on this. As much as the crash sucks, I’d still rather keep dealing with it to get the benefit…

**Comment by s-KaiNet** [comment]
@andrewconnell Actually `gulp-webpack` is renamed to [`webpack-stream`](https://github.com/shama/webpack-stream) (npm reports warning during `npm install`). JFYI `phatomjs` renamed to [`phantomjs-prebuilt`](https://github.com/Medium/phantomjs)  
I've tried `webpack-stream`, which is `3.1.0` - same result, same OOM exception.  
Previously you mentioned some "chore" work you are going to do. Can you please also include renaming aforementioned packages into this work?

**Comment by andrewconnell** [comment]
Yup... you bet... I just created an issue for it #161. I plan to do a lot of that work right after `uif-button` is finished
