### ISSUE TITLE
consider using ngMetadata

### ISSUE THREAD

**Issue by Hotell** [ngOfficeUIFabric/ng-officeuifabric#189]
Writting angular 1 with pure typescript isn't very convenient dev experience. Would you consider using ngMetadata  https://www.npmjs.com/package/ng-metadata ? It allows flawless gradual update, and your codebase will be ready for future migration to ng2. 

If you would be interested I can do PR with some component upgraded to ngMetadata.

Think about it :)

cheers
Martin

**Comment by andrewconnell** [comment]
The NPM page doesn't have enough info to really understand what's going on IMHO. I take it this is your library? Feel free to fork & propose but personally I'd need to understand more before putting this requirement on contributors.

FWIW, your comment "writing ng1 with pure typescript isn't ver convenient dev experience" is simply an opinion. We're doing quite well so far & I personally find it to be just fine.

**Comment by Hotell** [comment]
Yes @andrewconnell you are perfectly right about opinion etc. 
We used the same "design patterns" for writing ng1 with typescript as you do. 

But when Angular 2 core API went stable, I wrote ngMetadata to have cleaner code which makes sense IMHO. I've updated the `Readme` because it wasn't very clear from it what is it good for, please see that 1st example https://github.com/ngParty/ng-metadata. We are using it on production for our component framework internally. It supports all angular 1 API's which are covered behind nice Angular 2 API syntax.

I will migrate one of your components and do PR when I'll have little more time, hopefully till end this week as a showcase.

Thank you for hearing me out, I appreciate that :) and kudos to ngOfficeFabric!

**Comment by andrewconnell** [comment]
I’m curious to see what it looks like. Thanks for the kind comments too! Great team effort!

**Comment by ghost** [comment]
@Hotell  have you had time to create a showcase yet?

**Comment by Hotell** [comment]
@rolandoldengarm  I'm sorry I was supper busy by doing meetups/workshops .. you can imagine. I will do my best to do this till the end of this week. Thx!

**Comment by jorgearteiro** [comment]
@Hotell  I wanna see that as well. and what you think about version 1.5?

**Comment by Hotell** [comment]
@jorgearteiro angular 1.5 is a must ( one way binding, multi slot transclusion, lazy $compile, perf boost...). I plan to support only 1.5 and higher with ngMetadata 2.0. In 2.0 there will be one way binding by default. I didn't have again much time to do the PR, I will do that till end of this week and that's a promise. Sorry for waiting so long folks. Thanks

**Comment by Hotell** [comment]
https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/231

**Comment by andrewconnell** [comment]
_copied from PR comment here: https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/231#issuecomment-212852098_

Hey @Hotell ... sorry for letting this hang out there... but I think at this time we want to get the current push to 1.0 because we want to make sure we are at the same parity with coverage with Office UI Fabric for ng1 before we start work on ng2. I don't think many (if any other than @rolandoldengarm) have spent time with ng2 so we don't know what's in store. As such, I don't think we want to stop and look at what to do to be forward compatible.

In addition, the Angular Material guys are doing some work to add infrastructure we'd be able to leverage to make building for ng2 easier. For instance, I understand they are building a library / framework that will do screenshot of rendered components and diff them when tests run to see that the rendering didn't change & matches the spec. How will that (and other things) be impacted by using different upgrade options, I don't know... but waiting to see where they go first.

For now, I'm going to close this PR so it doesn't just hang out there, but this is definitely something we can look at later when we look to start work on the ng2 implementation of this project.

Thanks for submitting & adding the explanation above comparing the different upgrade options!

**Comment by Hotell** [comment]
> _copied from PR comment here: #231 [comment](https://github.com/ngOfficeUIFabric/ng-officeuifabric/pull/231#issuecomment-212863317)_

Hey @andrewconnell , yes I completely see and understand your point about pushing 1.0 as a priority. 

Few notes though:

about ngMaterial upgrade strategy:
- there will be no upgrade strategy from the code base point
- ngMaterial2 is being rewritten from scratch ( that's a good thing! ngMaterial 1 modularity === ZERO )

so in case of ngOfficeUiFabric you will have two options, when ngMaterial2 is finished and pushes out the correct implementation path:
- you rewrite UiFabric from scratch for ng2
- or you start preparation phase with ngMetadata after 1.0 of UiFabric which will allow you to easily migrate to ng2

Anyway good luck with the project and if you reconsider ngMetadata or want to ask anything related to ng2 or migration, don't hesitate to reach me. I'd love to help! 

thanks for hearing me out and cheers to whole ngUiFabric Team!
