### ISSUE TITLE
Component to create: orgchart

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#27]
Official link to component description & demo: http://dev.office.com/fabric/components/orgchart

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by SteenMolberg** [comment]
@andrewconnell : Hi AC, I would like to take a shot at this one

**Comment by andrewconnell** [comment]
:+1: you got it!

**Comment by SteenMolberg** [comment]
Would like comments please:)

``` html
    <uif-orgchart uif-items="vm.employees"                  
                uif-primarytext="Fullname" 
                uif-imageurl="Image"
                uif-secondarytext="Title"              
                uif-groupby="Department" 
                uif-presense="Presence" 
                uif-style="default|square"              
                uif-personaselectable="true"                
                uif-selectedpersona="{{vm.selectedEmployee}}" 
                uif-personaclick="vm.employeeClick()" />      

    <!--
        uif-items             ++ source array (required)
        uif-primarytext       ++ name of property used for primarytext, typical Fullname (required)
        uif-imageurl          ++ name of property used for image url (required)
        uif-secondarytext     ++ name of property used for secondarytext
        uif-groupby           ++ name of property used for group-title", if not provided => single group with no title
        uif-presence          ++ name of property used for presense, values available|away|blocked|busy, if not provived => no presence shown
        uif-style             ++ default is circle images and square is square images, if not provided => default circle
        uif-personaselectable ++ enable select persons
        uif-selectedpersona   ++ selected person-object passed to this 
        uif-personaclick      ++ function to execute when person is clicked
    -->
```

Have I missed something? I that what you @andrewconnell had in mind?

**Comment by waldekmastykarz** [comment]
Shouldn't the `uif-presense` attribute be called `uif-presence` instead?

Office UI Fabric refers to Org Chart as OrgChart rather than Orgchart. For consistency should we use `uif-org-chart` as the directive name?

A minor detail: shouldn't properties names begin with a lowercase letter (in case this sample ends up in the documentation :))?

**Comment by andrewconnell** [comment]
:+1:  to all @waldekmastykarz's comments. 

Also, any attributes that have multiple words (`uif-scondarytext`) should be broken out (ie: `uif-secondary-text`).

**Comment by SteenMolberg** [comment]
OK to all above. Thx

**Comment by waldekmastykarz** [comment]
One more: why is _selectedpersona_ bound as an expression while items are bound by name? Wouldn't it better if both properties worked the same? Wouldn't _selected_ be a property of objects in the _employees_ collection and could it be therefore bound the same way as other properties such as _primaryText_?

**Comment by SteenMolberg** [comment]
You are right @waldekmastykarz ... actually that was my intention. I would like to be able to provide a simple name or bind to a property.

Yes selected would be an object in the employees. It was not clear from my spec. By selecting a person the object would be assigned to a property. Is there a better way?

**Comment by waldekmastykarz** [comment]
Each persona could have a selected property:

``` js
var persona = {
  name: 'Joe Doe',
  selected: true
}
```

Then in the directive we could simply point to that property to render selected personas. Whether a persona is selected or not would be tracked in the persona object rather than on orgchart.

Speaking of which: how about we support support for three selection modes: none, single and multiple similarly as we will do in the table directive #61?

**Comment by SteenMolberg** [comment]
@waldekmastykarz agree to all... we save a property that way.  I take a look a table directive to keep consistent with the selection mode

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by johnmeilleur** [comment]
Suggestions:

`uif-style` - enum round, square (default to round)
`uif-presence` - enum available, away, blocked, busy, dnd, offline (default to offline)

See issue #31

**Comment by andrewconnell** [comment]
Touching base... how's it going with the directive?

**Comment by SteenMolberg** [comment]
Almost done. Missing most of the test though. I think I can submit for review within the next 2 days.

**Comment by andrewconnell** [comment]
Awesome... thanks! Just making sure it was still being worked on since we hadn't seen a PR or heard anything.

**Comment by SteenMolberg** [comment]
Hey guys,

I need your help to decide the approach to take...

I have a solution now that is implemented like in the spec above. But...

The discussion on the [personcard ](https://github.com/ngOfficeUIFabric/ng-officeuifabric/issues/32#issuecomment-180387784) the or other day and @andrewconnell comment on preferring elements over attributes, made me realize that the above spec is quite different from the approach that was suggusted for personcard and other directives as well.  In order to keep more i line with the rest the specs should maybe look more like this:

```
<uif-org-chart uif-items="vm.items" uif-select-mode="none|single|multiple" uif-selected="vm.selected" >
  <uif-org-chart-group ng-repeat="group in vm.persons | groupbyfilter: {{vm.groupbyfield}}" >
    <uif-org-chart-persona 
          ng-repeat="person in vm.persons | filter: getFilter(vm.groupbyfield, group)" 
          uif-style="standard|square" 
          uif-click="vm.personaClick">
      <uif-org-chart-image>{{person.image}}</uif-org-chart-image>
      <uif-org-chart-presence>{{person.presence}}</uif-org-chart-presence>
      <uif-primary-text>{{person.name}}</uif-primary-text>
      <uif-secondary-text>{{person.title}}</uif-secondary-text>
    </uif-org-chart-persona>
  </uif-org-chart-group>
</uif-org-chart>
```

Should I go for this spec instead?

I can see that this spec would give more flexibility, but if would make for at bit of extra work/hassle for the user in order to implement the grouping and filtering of the person-items provided.  Actually one of my goals was to do this work for the user, so I build that in to the current solution.

If  I should go the new spec I could use some suggestion on how to implement the grouping or it I should leave that to the user?

Thx for any feedback.

**Comment by andrewconnell** [comment]
Little more background into my thinking on element vs. attribute. My issue with attributes is they don't leave much room for options down the road. For some things it's not necessary (like binding items, grouping, image URLs, etc) but for other things, specifically text, it's very limiting because you can't do any formatting of the text. 

For instance, let's say the primary text needed to change colors between words or font weights (let's set aside the usability of that scenario for this discussion :smile: ).

So... looking at the original spec, I think the only attributes that should move to elements are the text ones (primary & secondary). Thoughts?

This might mean you don't have to redo any of your grouping logic?

**Comment by jjczopek** [comment]
totally agree with @andrewconnell . Having look into persona-card vs. persona vs. list, only the primary, secondary, tertiary and optional text were chosen as elements. Presence and image location did not, as those are rather static and have strict definition.

**Comment by SteenMolberg** [comment]
Well, I think any collection of directives should make my life easier as a developer. The solution I have now is very easy to use. Just apply some collection and propnames and you're of. The possibility to provide text by "transclusion" could be build in if the need occurs.

Maybe I should just submit the PR. You can always reject it.
