### ISSUE TITLE
Component to create: Facepile

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#275]
Official link to component description & demo: http://dev.office.com/fabric/components/facepile

Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv

**Comment by ghost** [comment]
I can pick this one up if you like, but before I spec it up, I have a few things we need to consider around what the scope of this directive should be - since the example on the Fabric site is quite complete.

There's a snippet in the fabric demo site (shown below) which hard codes a limit of five members. I think we should at the very least, make that number dynamic through the directive or, perhaps overflow facepile items in the same manner as `uifCommandBar` does (http://ngofficeuifabric.com/demos/uifCommandBar/), by putting overflowed items into a `uifContextualMenu`, thoughts @ngOfficeUIFabric/ngofficeuifabric-members?

``` javascript
          /** Display a maxiumum of 5 people */
           $(".ms-Facepile-members").children(":lt(5)").show();

          /** Display counter after 5 people are present */
          if ($membersCount <= 5) {
            $(".ms-Facepile-itemBtn--overflow").removeClass("is-active");
          } else {
            var remainingMembers = $membersCount - 5;
            $(".ms-Facepile-overflowText").text("+" + remainingMembers);
          }
        }
      }); 
```

Futhermore, the demo example has a persona card in each facepile item - should we leave it to the consumer to add a `uifPersonaCard` if they wish (we can provide demos with and without perhaps?). 

Finally, I'll be using `uifPersona` within the directive, so all `uifFacepile` will really do is handle the container and the overflowing of elements. Should we limit the size of the `uifPersona` to extra small, since that's the only option they show in the Fabric site - or should we allow the user the option (and default to extra small), I would suggest we offer the consumer the choice here.

**Comment by s-KaiNet** [comment]
hm...may be you need a wait for a while, until people picker will be ready, If you look closely into the source for demo, you will see that the right part is actually a people picker in facepile mode.  
Currently I'm working on it and it take up to two weeks to handle it.  
So actually your first question is about people picker :). For this question I'd rather have a dynamic value (good for start, then we can adjust this later if required).  
I think we leave an option to add persona card to the developer.

**Comment by ghost** [comment]
The facepile rendered at the start (i.e. not in the panel) is the one affected by that code snippet is it not? Adding more members to the people picker in facepile mode affects the facepile as shown below...

![image](https://cloud.githubusercontent.com/assets/13330650/14443369/b57e2dee-0036-11e6-9982-9f6c89ca6993.png)

I'm happy to wait or leave it for someone else of course, but can start and plug in the people picker with facepile mode afterwards. I certainly wouldn't PR before the people picker has been completed as there is a dependency there.

**Comment by s-KaiNet** [comment]
You're right, you can start right now if you want. I've just pushed into my fork here - [issue-30](https://github.com/s-KaiNet/ng-officeuifabric/tree/issue-30). Grouped demo completely ready, it can be changed, but I believe that interface for communicating with "other world" will remain the same - `demo\index.html` - `<uif-people-picker uif-people="onSearch(query)" ng-model="selectedPeople">` where `selectedPeople` is array of `PersonPicker` (you can find it in code). May be that's enough for you to work with facepile, later as you said you can plug picker in facepile mode easily.

**Comment by ghost** [comment]
# Facepile Directive Spec

``` html
<uif-facefile ng-model="vm.SiteMembers" uif-overflow-limit="5">
 <!--optional-->
 <uif-facepile-add-icon
    uif-panel-header-text="Members"
    uif-people="onSearch(query)"
    uif-selected-people="selectedPeople"
    placeholder="Add Members..."/>
</uif-facepile>
```

### uif-facepile

Directive container, handles the creation of the DOM and binding of any events for interacting with each FacePile icon.
- ng-model - contains the Person collection
- uif-overflow-limit - optional, the maximum number of `<uif-facepile-person>` items to display before overflowing.

### uif-facepile-add-icon

Optional, Shows the 'add' icon and generates the appropriate `<uif-panel>` and `<uif-people-picker>`
- uif-panel-header-text - defines the text to show in the `<uif-panel>`, above the `<uif-people-picker>`
- uif-people - method returns an array of, or promise for a collection of Persons, as defined in `<uif-people-picker>`
- placeholder - string which contains the placeholder for the people picker

**n.b.** ng-model from `<uif-people-picker>` not defined in here, since that will be the ngModel in `<uif-facepile>` More may be added once integrated here with the final release of `<uif-people-picker>`, but these should dovetail in as new attributes painlessly.

### Reuse of Person object

As described in #30.

 I was toying with creating a FacePilePerson object which would be simplified, but since the `<uif-facepile>` and it's child `<uif-people-picker>` need to interact I decided not to. FacePile does technically not need the `primaryText` attribute, which is required by `Person` but I feel this is a reasonable overhead. @andrewconnell, should we consider using the Person object in `uifPersona` too at some point? I see `Person` will live in /src/core in your fork @s-KaiNet which makes perfect sense.

**Comment by s-KaiNet** [comment]
I look into panel demo and didn't find facepile mode or something. Can you please elaborate why would it be replaced by the `uif-panel-header`?

**Comment by andrewconnell** [comment]
The spec feels like a mix of a directive and usage, by that I mean that there are a few things that are facepile, but there is a lot of “here’s how you use the other directives. Is there a reason why you have to manually list the `uif-persona` & `uif-people-picker` components?

It would see to me that the ideal spec would be to make the developer know how to use only this directive, `uif-facepile`, and not have to learn how to use the other directives as well… something more like:

```
<uif-facepile uif-people="{{collection-of-objects-with-initials-and-color}}” uif-overflow-limit=“5” uif-selected-people-header=“”>
  <uif-facepile-add-icon ng-click=“AddMembers()”  />
</uif-facepile>
```

If there’s an add icon, then people can search, so that would cause the directive to add the panel. You can add panel-specific attributes like the search delay, model, people to search on, the event handler when someone is clicked to the add element.

Further, why is a header for the label needed?

To me, this seems like a simpler option. A lot of the stuff in the spec you have seems like it could be figured out for the developer automatically within the facepile directive.

Thoughts?

**Comment by ghost** [comment]
That approach makes sense @andrewconnell, and I guess it will also negate the need for validation of the `uif-size`, will update spec above by this evening. At a first glance I would move`<uif-selected-people-header>` to the `<uif-facepile-add-icon>`, simply because the panel only gets shown when adding user - but otherwise looks great.

Regarding the question around headers for the panel both @andrewconnell  and @s-KaiNet asked - if you take a look the markup in the Fabric site for [panels](http://dev.office.com/fabric/components/panel), the header text is within an element with the `.ms-Panel-headerText`, then the content is wrapped in a `.ms-Panel-content`. `<uif-panel-header>` & `<uif-content>` within the panel directive handle this for the consumer.

![image](https://cloud.githubusercontent.com/assets/13330650/14637207/bf90568a-0627-11e6-9e06-743c99766c74.png)

For the Facepile example [here](http://dev.office.com/fabric/components/facepile), there seems to be an inconsistency in that `.ms-PeoplePicker` is not within a `.ms-Panel-content` div, I think that's an omission in Microsoft's part during the creation of the demos.

![image](https://cloud.githubusercontent.com/assets/13330650/14637190/a56ba994-0627-11e6-83bb-18f16ae24d4e.png)

This is why I suggested to @s-KaiNet that `<uif-facepile-header>` wouldn't be required in `uifPeoplePicker`, but is needed in `uifFacepile` - since the consumer needs to be able to control what text gets displayed in the panel, and the only time `uifPeoplePicker` uses Facepile mode, is in this particular scenario.

**Comment by andrewconnell** [comment]
Sounds good… looking forward to the updated spec.

As for the inconsistency in their demo, I’d file an issue with Fabric as I’m sure they’ll address it based on their recent activity.

**Comment by s-KaiNet** [comment]
@tobiaswest83 now I see...thanks for explanation. We have two headers - one for the panel and one for the people picker in facepile mode. No need to have two identical headers.. correct?  
Then I will make sure that when `uif-facepile-header` is omitted all other parts look and work as expected.  
@andrewconnell I've prepared a list of issues\question regarding people picker demo and people picker itself. Office UI's people picker story looks for me a bit unfinished, just imho.

**Comment by ghost** [comment]
@andrewconnell - updated spec above

**Comment by s-KaiNet** [comment]
JSFYI
I had to leave `uif-facepile-header` as is, because people picker has some styling issues when missing facepile header.

**Comment by andrewconnell** [comment]
Looking at the new peoplepicker directive, I see facepile in it... does that mean we don't need a separate directive for facepile?

**Comment by ghost** [comment]
The `uifFacepile` directive is the combination of collection of `uifPersona` directives, and the `uifPeoplePicker` (in facepile model), nested inside a `uifPanel`, so yes - I believe it's still needed.

**Comment by ghost** [comment]
@andrewconnell you OK with the design so I can crack on? :smile:

**Comment by andrewconnell** [comment]
LGTM... go for it! :)

**Comment by andrewconnell** [comment]
Checking in on this directive as doing a v1.0 release review... can you provide a status on this directive @tobiaswest83 ?

**Comment by ghost** [comment]
hi @andrewconnell, should be done by the weekend - sorry for the slow progress, been super busy

**Comment by andrewconnell** [comment]
No worries... just checking in. Thanks for the update!

**Comment by ghost** [comment]
Sorry for delay on this, had a few issues and then been working away. Will be finishing tests and putting PR together in next day or two
