### ISSUE TITLE
Component to create: panel

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#29]
Official link to component description & demo: http://dev.office.com/fabric/components/panel

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by ghost** [comment]
Shall I spec this and pick it up next?

**Comment by andrewconnell** [comment]
Sure! Go for it!

**Comment by ghost** [comment]
## uif-panel Spec

``` html
<uif-panel uif-type="medium" uif-is-open="true" uif-show-close"false" uif-show-overlay="true">
   <uif-panel-header>
     <uif-content>Hello World!</uif-content>
   </uif-panel-header>
   <uif-content>User content.....</uif-content>
</uif-panel>
```

## Parameters

### uif-type

Enum, allows for left, small, medium, large, extraLarge, lightDismiss

### uif-is-open

Boolean, controls visibility of panel. does additional animation etc, so ngShow would not suffice

### uif-show-overlay

Shows the overlay, true by default

### uif-show-close

Shows the close button, true by default

## Notes

Suggest that if the consumer includes a `<uif-command-bar/>`, the directive adds the appropriate wrapper rather than make the markup any more complicated than it needs to be.

**Comment by ghost** [comment]
I've got two questions:
- What about closing a Panel? You can add a command bar, but how can you close that panel from that command bar?
- How to open a Panel? A Panel consists of the panel content as you've specced, but also a button to open it.

It is a bit similar to the Dialog, as you can open and close it from an arbitrary button.

I think the header should indeed be just text.

**Comment by ghost** [comment]
I neglected to include a uifIsOpen attribute to <uif-panel> which I'll include. This attribute can manage the animation and visibility state of the panel. Regarding a button to control it, I intend to add a <uif-button> in the sample to demonstrate how to show/hide but I wouldn't include this button in the directive, presume this is what you mean?

Closing a panel is done by a close icon within the panel within the Fabric samples. I intended to bake this into the template unless we should create an attribute called uifShowClose to determine whether a close 'x' is displayed and is actionable?

I'll update spec once feedback gathered, thanks for input :)

**Comment by ghost** [comment]
Ah you won't need a service then (that's my initial guess), the developer needs to have a scope variable, assign it to uifIsOpen, and set it to true / false in a custom button click?
Same for the closing? 
That looks good to me.

No,  you should not add the button to open/close the dialog to the directive, just want to make sure you can open the panel :+1:

**Comment by andrewconnell** [comment]
The header text should not be in an attribute... IMHO it should be added as content. See the new `uif-content` directive that was recently added if you want to use that. While plain text is all that the demos use today, if Fabric changes the CSS to make it work with rich content, then we have a breaking change we have to introduce. This pattern will follow how other directives work.

For the `uif-type`, please spell out the sizes... don't use abbreviations as other directives don't follow that pattern.

**Comment by ghost** [comment]
I've updated the spec to reflect feedback. 

@andrewconnell, I'm not sure using `uif-content` within `uif-panel-header` will make sense since it's so close in name to `uif-panel-content`, let me know your thoughts if you want me to though

**Comment by andrewconnell** [comment]
So... looks like we have two content areas... and both should just be transcluded. How is `uif-panel-content` special? 

This seems to make sense to me...

``` html
<uif-panel uif-type="medium" uif-is-open="true" uif-show-close"false" uif-show-overlay="true">
   <uif-panel-header>
     <uif-content>Hello World!</uif-content>
   </uif-panel-header>
   <uif-content>User content.....</uif-content>
</uif-panel>
```

**Comment by ghost** [comment]
There's nothing special about it, I'll update the spec to reflect your suggestion - this will negate the need for `uif-panel-content` and i'll make a start unless there are any other suggestions

**Comment by ghost** [comment]
Why not use uif-header-content and uif-panel content? I don't see the need for an extra uif-panel-header directive?

**Comment by andrewconnell** [comment]
Good point... we recently got the `uif-content` directive for nesting content... how would you propose not inventing something else?

**Comment by ghost** [comment]
That was my original intention, I think @andrewconnell wanted consistency between directives. 

The option below would be the absolute minimum, it saves creating `uif-panel-content`, so I would agree with AC's approach here. Wasn't sure on the use for a `uif-content` within the `uif-panel-header` directive - can we do away with that and use the pattern below? Or would you want to keep it consistent? 

``` html
<uif-panel uif-type="medium" uif-is-open="true" uif-show-close"false" uif-show-overlay="true">
   <uif-panel-header>Hello World!</uif-panel-header>
   <uif-content>User content.....</uif-content>
</uif-panel>
```

**Comment by andrewconnell** [comment]
Let's continue to debate this... 

I still like my proposal above. The reason why is because the 'uif-content' has one purpose to render content. The trick is you need to have one bit of content be header content. So I think it makes sense to wrap it because the metaphor holds true. 

Empty containers aren't new or rare.. Think 'thead'

... Grr... Can't get the code formatting right on an iPad ... You get the picture :)

**Comment by ghost** [comment]
I can see both sides of the argument. Having uif-content within uif-panel-header ensures consistency with other directives but since uif-panel-header's sole purpose is to be a transcluded container for the header text (or richer content in the future), the inclusion of uif-container could be seen as redundant. 

Both will work, I think the decision comes down to how and when we should use uif-content. In my humble opinion, it should be used to _replace_ the need for adding additional directives within a component (removing uif-panel-container is an example of this), otherwise we may set a precident which means uif-content ends up appearing all over the place. 

Sorry AC....another directive, another debate :D

**Comment by andrewconnell** [comment]
I'd love to see more comments here as I think we are simply down to preference... @ngOfficeUIFabric/ngofficeuifabric-collaborators ?

**Comment by jorgearteiro** [comment]
I agree with tobias. uif-panel-header is already a transcluded container. Less is better!

**Comment by ghost** [comment]
I agree with @jorgearteiro  and @tobiaswest83 .
I don't see a benefit to have two directives, instead of one. E.g. if in the future we want to add an attribute to the header (e.g. large / small / whatever), it is possible with one directive.
Only advantage of having 2, is that uif-content is the same as in other directives. But IMHO that's not a reason why we should do this, but that's just my opinion.

**Comment by ghost** [comment]
how should we proceed @andrewconnell? I'm working away this week so can't start until next weekend but this won't take me long once we've agreed spec.

**Comment by andrewconnell** [comment]
Seems I'm out voted... I think it's good to go ahead and implement

**Comment by ghost** [comment]
I'm nearly there with this, just battling a jasmine test and making sure code coverage is as close to 100% as possible, expect to submit PR this weekend
