### ISSUE TITLE
Component to create: peoplepicker

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#30]
Official link to component description & demo: http://dev.office.com/fabric/components/peoplepicker

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by andrewconnell** [comment]
This should also include the **facepile** component that Fabric added in v2.x. While it shows up as a separate component in the Fabric distro, if you look at the demo for **peoplepicker** in Fabric's samples, you can see it's just a different rendering.

**Comment by s-KaiNet** [comment]
I'm taking this one.

**Comment by s-KaiNet** [comment]
@andrewconnell imho, FacePile should be a separate component. FacePile demo uses people picker in facepile mode, but FacePile itself is not a people picker, it only uses it. Are you agree?

**Comment by s-KaiNet** [comment]
## **SPECS:**

``` html
<uif-people-picker 
uif-people="onSearch(query)" 
ng-model="people" 
uif-type="compact|Facepile|membersList|<empty(default)>"
placeholder="placeholder">
    <uif-people-search-more uif-type="disconnected|<empty(default)>" uif-icon="searchIcon">
        <uif-primary-text></uif-primary-text>
        <uif-secondary-text></uif-secondary-text>
    </uif-people-search-more>
    <uif-selected-count></uif-selected-count>
    <uif-members-list ng-click="onMemberClick"></uif-members-list>
</uif-people-picker>
```

##### `<uif-people-picker>` - main directive
- `uif-people` - `&uifPeople` - method returns array of persons or angular promise resolving array in order to populate a picker.  
  There can be two approaches how to show data from array. One option is to provide property names for person object through the `<uif-people-picker>` attributes (i.e. `<uif-people-picker uif-person-primary-text="personNameProperty" uif-person-icon="iconProperty"...>`, than inside directive `peopleArray[0].personNameProperty` returns person's name). Another option is to use convention over configuration and expect every array element to be in a certain format. 
  I selected the last one, because the number of properties is big and markup looks really ugly when you provide all of them.  
  That means that directive expects an array of objects returned by `uif-people` method (or promise) having certain format (I'm refer it as `Person` object, specs for `Person` in the bottom)    
- `ng-model` - `=ngModel` - array of `Person` objects, representing items selected in people picker    
- `uif-type` - `@uifType` - people picker type. Can be `compact`, `Facepile`, `membersList`, or empty (default empty if not provided)  
- `placeholder` = `=placeholder` - placeholder for picker input, used only in `Facepile` mode, in other modes ignored    

##### `<uif-people-search-more>` - helper directive for the bottom of the people picker
- `uif-type` - `=uifType` - type of the "search more" component. Can be disconnected or empty (normal default state)  
- `uif-icon` - `=uifIcon` - icon used for search  
- `<uif-primary-text>` - primary text placeholder
- `<uif-secondary-text>` - secondary text placeholder

##### `<uif-selected-count>` - directive used only in `membersList` and `Facepile` modes. Used to specify custom text for selected persons

##### `<uif-members-list>` - directive used only in `membersList` and `Facepile` modes. Used to render list of selected persons and optionally set a click handler (for example for displaying persona card by clicking on persona)

#### `Person` object:
- `icon` - string, optional, but either `icon` or `initials` should be provided  
- `initials` - string, optional, but either `icon` or `initials` should be provided  
- `primaryText` - string, required
- `secondaryText` - string, optional
- `color` - string, ignored if `icon` provided, required if `initials` provided, detemines background color for initials  
- `presence` - string, optional, default is `Offline`  
- `group` - object, optional, determines group for person ("Top Results", "Other Results", etc.), `name` - group name, `order` - specifies group ordering
- `additionalData` - array of `Person` objects, if present near the search result will be an `shevronDown` arrow displaying additional persons

![2016-04-09_2312](https://cloud.githubusercontent.com/assets/10658276/14406182/fe3b6d6a-fea8-11e5-85e1-60311d04ee1a.png)

Looking for feedback, @ngOfficeUIFabric/ngofficeuifabric-members , but the docs and demo in Office UI Fabric for people picker a bit strange and has many gaps. I spent more than three hours producing this spec only.

**Comment by s-KaiNet** [comment]
Link to working [plnkr](http://plnkr.co/edit/BMxr8TAOagBF987ImK7n?p=preview) for people picker (with my fixes, because on the fabric site and in repository some demos are not working).

**Comment by andrewconnell** [comment]
> FacePile should be a separate component. FacePile demo uses people picker in facepile mode, but FacePile itself is not a people picker, it only uses it. Are you agree?

Agreed... I'll setup a new issue for Facepile

**Comment by andrewconnell** [comment]
Very well written up spec... I agree that Facepile should be it's own component & have created a new issue reflecting it: #275. Spec looks good to me!

**Comment by andrewconnell** [comment]
One thing to add... make sure that `disabled` and `ng-disabled` are also included in the cases. We have missed `ng-disabled` in many components.

**Comment by s-KaiNet** [comment]
People picker doesn't have disabled state, so I'll skip this.

**Comment by andrewconnell** [comment]
Shouldn't we offer it though? It's an input control so logic would seem to assume you could disable it. IMHO it would be odd if you had 5 controls on a form and could disable just 4 of them.

**Comment by s-KaiNet** [comment]
That makes sense, if some styles will be required from Office UI side I will report a bug.

**Comment by jjczopek** [comment]
I think it makes a lot of sense in general - great spec! In order not to reinvent some of the things, you might want to reuse:
- color for initials: https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/core/personaInitialsColorEnum.ts
- presence indication: https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/core/personaPresenceEnum.ts
