### ISSUE TITLE
Component to create: persona

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#31]
Official link to component description & demo: http://dev.office.com/fabric/components/persona

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by johnmeilleur** [comment]
**SPEC**

First revision

main component directive: `<uif-persona></uif-persona>`
optional enum attribute uif-style = round, square.  Defaults to round
optional enum attribute uif-size = tiny, xsmall, small, medium, large, xlarge.  Defaults to medium
optional enum attribute uif-presence = available, away, blocked, busy, dnd, offline.  Defaults to offline
optional string attribute uif-image-url.  If not set show a default persona image.
optional string attribute uif-primary-text
optional string attribute uif-secondary-text

examples:
`<uif-persona uif-primary-text="John Doe" uif-secondary-text="Accountant" uif-presence="away" />`
`<uif-persona uif-primary-text="Alton Lafferty" uif-secondary-text="Information Technology" uif-imageurl="alafferty.jpg" />`

Aligning with #27

**Comment by andrewconnell** [comment]
LGTM!

**Comment by waldekmastykarz** [comment]
:+1:

**Comment by jjczopek** [comment]
looking forward!

**Comment by andrewconnell** [comment]
Touching base... how's it going with the directive?

**Comment by jjczopek** [comment]
@johnmeilleur how it's going with this one? I have just finished working on PersonaCard (#32, PR #223) and I believe I duplicated some if not all of your work. 

Maybe we could take the out common persona functionality out of persona card to this component and then in PersonaCard reuse the new Persona component?

**Comment by jjczopek** [comment]
Actually I have taken the liberty to implement this components as I already had the base from persona-card component.

Adjusted spec of the component, following our guidelines.

### `uif-persona-*-text` directives

Directives for user details:

``` html
<uif-persona-primary-text>Alton Lafferty</uif-persona-primary-text>
<uif-persona-secondary-text>Interior Designer, Contoso</uif-persona-secondary-text>
<uif-persona-tertiary-text>Office: 7/1234</uif-persona-tertiary-text>
<uif-persona-optional-text>Available - Video capable</uif-persona-optional-text>
```

### `uif-persona-initials` directive

Displays user initials when picture is not specified:
`<uif-persona-initials uif-color="blue">AL</uif-persona-initials>`
Attributes:
- `uifColor` - specifies the color of the initials placeholder. Available color are defined in `PersonaInitialsColor` enum. Available values: `lightBlue|blue|darkBlue|teal|lightGreen|green|darkGreen|lightPink|pink|magenta|purple|black|orange|red|darkRed`. Default: `blue`.

### `uif-persona` directive

Main directive
`<uif-persona uif-style="round" uif-size="small" uif-presence="offline"></uif-persona>`
Attributes:
- `uifStyle` - style of the persona component. Valid values: `round|square`. Default: `round`
- `uifSize` - size of the persona component. Valid values: `tiny|xsmall|small|medium|large|xlarge`
- `uifPresence` - presence of the associated user. Valid values: `available|away|blocked|busy|dnd|offline`. Default: `offline`

### Complete example

``` html
<uif-persona uif-style="square" uif-size="xlarge" uif-presence="dnd">
    <uif-persona-initials uif-color="blue">AL</uif-persona-initials>
    <uif-persona-primary-text>Alton Lafferty</uif-persona-primary-text>
    <uif-persona-secondary-text>Interior Designer, Contoso</uif-persona-secondary-text>
    <uif-persona-tertiary-text>Office: 7/1234</uif-persona-tertiary-text>
    <uif-persona-optional-text>Available - Video capable</uif-persona-optional-text>
</uif-persona>
```

**Final thoughts**
The at leas two more components that are related to `persona` component: `personaCard` and possibly `orgChart` (@SteenMolberg)  . I think it would be good to reuse this component in those two if you agree. I have already submitted the PR for `personaCard` but it this component would also be approved, I would rewrite part of it to reuse `persona` component instead of duplicating the effort. Please share your thoughts on this.

**Comment by johnmeilleur** [comment]
Hi @jjczopek,

Sorry, I've been away.  Fantastic work on the persona card.  No worries if you want to finish the persona.
