### ISSUE TITLE
uif-textfield: multiline: ng-list and ng-trim not supported

### ISSUE THREAD

**Issue by andikrueger** [ngOfficeUIFabric/ng-officeuifabric#328]
### Expected Behavior

uif-textfield as multi line does support ng-ist and ng-trim
### Actual Behavior

uif-textfield as multi line does not support ng-list and ng-trim not supported
### Steps to Reproduce Behavior

[https://plnkr.co/edit/qywXx74oGnn5x3Tm0ptL?p=preview](https://plnkr.co/edit/qywXx74oGnn5x3Tm0ptL?p=preview)

**Comment by andikrueger** [comment]
I think, we can put this issue on hold, as there is an issue with the ngList attribute. ngList does not support dynamic list delimiter, which are a precondition to use the attribute in template.

The corresponding angular issue:
[ngList renders scope variable instead of the value](https://github.com/angular/angular.js/issues/14624)

**Comment by andrewconnell** [comment]
I'm going to close this. Because the underlying Angular directive doesn't support it, it's not something we can address. Would be better if we contributed to the core Angular library to support the interpolation of the condition then we can add support to our library... but for now, doesn't seem like something we can address.
