### ISSUE TITLE
uif-Breadcrumb: missing responsiveness

### ISSUE THREAD

**Issue by andikrueger** [ngOfficeUIFabric/ng-officeuifabric#342]
### Expected Behavior

Breadcrumb shows the last 2 or 4 link elements dependent on the screen size:
[Demo Office Ui Fabric](http://dev.office.com/fabric/components/breadcrumb)
### Actual Behavior

uif-breadcrumb renders all link elements. [Breadcrumb.js](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Breadcrumb/Breadcrumb.js) code is missing in the directive.

**Comment by andrewconnell** [comment]
Good find... bugging this. 

BTW, we don't include the JavaScript from Office UI Fabric since historically they take dependencies on jQuery (I'm aware this is changing). We want to only require users to reference out JS file, not additional files if possible. In the past we've taken the approach that the JS should be rewritten into our component.

**Comment by andikrueger** [comment]
That was more kind of a reminder where to find the "responsiveness". Hopefully the Office Ui Fabric guys will make  good progress with this Typescript topic and will save us a lot of time rewriting the code.

**Comment by andrewconnell** [comment]
But we don’t want to take a dependency on their JavaScript… we haven’t in the past because of issues they’ve faced. As a project principal, all the script they produce is example stuff… it’s not shipped with the components except with their examples. For instance, it’s not included in their CDN updates… they only ship their CSS.

Unless there’s a compelling reason we should keep with our position of not including any 3rd party JS libraries, including those from Office UI Fabric.

The only exception we’ve made to date is the date picker because it’s impossible to get around it… but my understanding is they are also trying to get away from their dependency on pickadate.js.

**Comment by jjczopek** [comment]
Is any one looking into this? I wouldn't like to duplicate effort.

**Comment by andikrueger** [comment]
Though I opened the issue, I haven't had the time to fix it jet.

**Comment by jjczopek** [comment]
Ok, so I'll start working on it.

**Comment by jjczopek** [comment]
The way how resposivness for this component works, is that if there are more elements to display than allowed (e.g. 4), some of the lements are moved from breadcrumb link list to contextual menu that is hidden under ellipsis icon.

I'm not sure if that's the best idea to move elements between DOM elements if e.g. ng-repeat is used (not even sure if that's possible).

I think the cleanest solution would be to use similar approach as Pivot component, where items are supplied by an attribute that is an array of elements. It would make the internal implementation cleaner.

That however would be a breaking change. 

My propsed changes to specs:
`<uif-breadcrumb uif-links="vm.breadcrumbLinks"></uif-breadcrumb>`

`breadcrumbLinks`would be an array of elements with following properties:
    - `href`\- where the item should lead to
    - `linkText`\- text to be placed between <a></a> tags
    - `isOverflow`\- whether this element should be overflow (in contextual menu) or not (breadcrumb links list)

And internally there would be two ng-repeats for contextual menu and breadcrumb link list, using the same elements array with different filters.

Let me know how do you feel about that.

**Comment by andikrueger** [comment]
I like the new specs. On the one hand it makes the uif-breadcrumb even more handy and the transclude function is getting easier. On the other hand this solutions eliminates a hard-coded breadcrumb.

I just opened my vs code and gave a double transclue function a try. There is something I don't like about appending the current transcluded elements twice. The resulting html is way bigger than needed.

I would refine your specs as followed:

``` html
<uif-breadcrumb uif-breadcrumbLinks="vm.breadcrumbLinks"></uif-breadcrumb>
```

vm.breadcrumbLinks would be an array of elements with following properties:
- `href`\- where the item should lead to
- `linkText`\- text to be placed between tags

I think the property `isOverflow` is not needed, as this should be done by the ng-repeat filter or is there any other use case I haven't seen?

I think the first ng-repeat (overflow)  should only render the first breadcrumbLinks.lenght-2 or breadcrumbLinks.lenght-4 elements, the second on, the last 2 or for 4 elements depending on the screen width.
