### ISSUE TITLE
Component to create: spinner

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#35]
Official link to component description & demo: http://dev.office.com/fabric/components/spinner

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by andrewconnell** [comment]
Claimed by @jjczopek

**Comment by jjczopek** [comment]
I've drafted initial spec for the spinner component:

``` html
<!-- 1. Simple spinner -->
<uif-spinner ng-show="showSpinner"></uif-spinner>

<!-- 2. Spinner with message -->
<uif-spinner ng-show="showSpinner">
  <uif-spinner-message>{{spinnerMessage}}</uif-spinner-message>
</uif-spinner>

<!-- 3. Separate directive for normal/large spinner? -->
<!-- Spinner - Large -->
<uif-spinner-large ng-show="showSpinner"></uif-spinner-large>

<!-- 4. Spinner with message - Large -->
<uif-spinner-large ng-show="showSpinner">
  <uif-spinner-message>{{spinnerMessage}}</uif-spinner-message>
</uif-spinner-large>

<!-- 5. Attribute directive for normal/large spinner? -->
<!-- Spinner - Large -->
<uif-spinner ng-show="showSpinner" uif-spinner-large></uif-spinner>

<!-- 6. Spinner with message - Large -->
<uif-spinner ng-show="showSpinner" uif-spinner-large>
  <uif-spinner-message>{{spinnerMessage}}</uif-spinner-message>
</uif-spinner>

<!-- 7. Attribute directive for normal/large spinner and message? -->
<!-- Spinner with message - Large -->
<uif-spinner ng-show="showSpinner" uif-spinner-large uif-spinner-message="{{spinnerMessage}}">  
</uif-spinner>
```

**Open topics:**
**Normal/Large spinner**
Fabric defines two types of spinners - normal (`ms-Spinner`) and large (`ms-Spinner ms-Spinner--large`). I'm wondering what would be the best approach to differentiate:
- create separate element directives `uif-spinner` and `uif-spinner-large` (example 1. & 3.) - hopefully it could reuse the same codebase with some conditional logic - in worst case scenario we would end up with duplicated code
- create attribute directive for large spinner `uif-spinner-large` (example 5.) - I think @andrewconnell  mentioned we should avoid attribute directives

**Message/label for spinner**

There is also possibility to show spinner with message - similar question as with large spinner:
- create separate element directive for message (example 2., 4. & 6.)
- create attribute directive (example 7.) - could be placed on the spinner element instead of nesting it with spinner directive.

**Additional JS**
Spinner component that currently is in master branch of fabric repo has a JS file, which defines the animation of the spinner as well as initialization of the component [Spinner.js](https://github.com/OfficeDev/Office-UI-Fabric/blob/master/src/components/Spinner/Spinner.js). 
Easiest way would be to include that file and leverage it's. 

Will _ngOfficeUiFabric_ include all of the necessary Fabric assets or users/authors would need to reference fabric separately? I think it would be good to bundle it all together in order to have control over the assets we are using - e.g. spinner JS file.

**Comment by waldekmastykarz** [comment]
**RE: Size**: Given that the only thing different between the large and the small spinner is its size, I'd vote for an attribute such as `uif-spinnersize` that would default to **small** and optionally could be set to **large**, eg.

``` html
<uif-spinner ng-show="showSpinner" uif-spinnersize="large">This shouldn't take long...</uif-spinner>
```

**RE: Message**: A message could theoretically contain HTML so with that it would be better to define it in content rather than using an attribute (options 2, 4 and 6). I think it's also worth researching if there are any other scenarios where we might want to nest anything else in `uif-spinner`. If not it would be easier to skip the `uif-spinner-message` directive and include the message directly within `uif-spinner` (see the example above).

``` html
<uif-spinner ng-show="showSpinner">This <b>shouldn't</b> take long...</uif-spinner>
```

vs.

``` html
<uif-spinner ng-show="showSpinner" uif-message="This <b>shouldn't</b> take long..."></uif-spinner>
```

**RE: Additional JS**:
I believe that what we discussed in #36 is that any JS files in Office UI Fabric are sample implementations and not something we should take dependency on. Wouldn't it be easier to look at the sample code but incorporate it in our directives so that we can easier add to it in the future? This would also prevent us from additional complexity of managing dependencies and having to load additional files.

**Comment by jjczopek** [comment]
Following @waldekmastykarz input, have a look at second draft of spinner specification:

**Normal spinner without message**

``` html
<uif-spinner ng-show="showSpinner"></uif-spinner>
<uif-spinner ng-show="showSpinner" uif-spinnersize="small"></uif-spinner>
```

**Normal spinner with message**

``` html
<uif-spinner ng-show="showSpinner">This shouldn't take long...</uif-spinner>
<uif-spinner ng-show="showSpinner" uif-spinnersize="small">This shouldn't take long...</uif-spinner>
```

**Large spinner without message**

``` html
<uif-spinner ng-show="showSpinner" uif-spinnersize="large"></uif-spinner>
```

**Large spinner with message**

``` html
<uif-spinner ng-show="showSpinner" uif-spinnersize="large">This shouldn't take long...</uif-spinner>
```

**Additional points**
- spinner logic (animation) that is handled by sample JS file in Fabric, will be adapted and incorporated into the directive source,
- if there is a message (content between start & end tag), make sure it's wrapped with `<div class="ms-Spinner-label"></div>`.

**Comment by waldekmastykarz** [comment]
Looks good to me.

**Comment by andrewconnell** [comment]
:+1: 

WRT the animation point, we do want to avoid any requirement to add another JS library just to make our stuff work. Ideally there are only two dependencies that ngOfficeUiFabric should take: 
- CSS from Office UI Fabric
- JS from Angular
