### ISSUE TITLE
Component to create: table

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#36]
Official link to component description & demo: http://dev.office.com/fabric/components/table

_Screenshot of web analytics for the original http://officeuifabric.com site by @andrewconnell. Use this to see what are the most popular components: http://imgur.com/gallery/buUcyQv_

**Comment by waldekmastykarz** [comment]
Shall I pick this up?

**Comment by andrewconnell** [comment]
This is going to be a big one... A really big one as we want more than just what fabric gives us... We want sortable columns, selectable rows, etc... Functionality that is expected in a directive... You sure you want to bite this off as your first one? 

This one def needs a spec agreed upon before someone starts building it out.

**Comment by waldekmastykarz** [comment]
I thought I'd do the basics first so that we can align with the Fabric for the basic use cases. If you'd rather see it all done at once then it would be definitely better to get the specs in place first to have a common understanding what we're after. We could then split it into separate items for easier tracking.

**Comment by andrewconnell** [comment]
Can always release iteratively…

p1 – feature equivalent
P\* - selectable rows / cells
P\*  -– sortable columns
p\* - etc

You still want it? :)

**Comment by waldekmastykarz** [comment]
How about I take p1? Others are still welcome to jump in and help with pX :)

**Comment by andrewconnell** [comment]
You own `<uif-table>`... first up, spec it :)

**Comment by waldekmastykarz** [comment]
Spec for p1 (based on http://dev.office.com/fabric/components/table):

```
<uif-table>
  <uif-tablerow>
    <uif-tablerowcheck></uif-tablerowcheck>
    <uit-tablecell>File name</uif-tablecell>
    <uit-tablecell>Location</uif-tablecell>
    <uit-tablecell>Modified</uif-tablecell>
    <uit-tablecell>Type</uif-tablecell>
  </uif-tablerow>
  <uif-tablerow>
    <uif-tablerowcheck></uif-tablerowcheck>
    <uit-tablecell>file1.txt</uif-tablecell>
    <uit-tablecell>./file1.txt</uif-tablecell>
    <uit-tablecell>2016-01-01</uif-tablecell>
    <uit-tablecell>txt</uif-tablecell>
  </uif-tablerow>
  <uif-tablerow selected>
    <uif-tablerowcheck></uif-tablerowcheck>
    <uit-tablecell>file2.txt</uif-tablecell>
    <uit-tablecell>./file2.txt</uif-tablecell>
    <uit-tablecell>2016-01-01</uif-tablecell>
    <uit-tablecell>txt</uif-tablecell>
  </uif-tablerow>
  <uif-tablerow>
    <uif-tablerowcheck></uif-tablerowcheck>
    <uit-tablecell>file3.txt</uif-tablecell>
    <uit-tablecell>./file3.txt</uif-tablecell>
    <uit-tablecell>2016-01-01</uif-tablecell>
    <uit-tablecell>txt</uif-tablecell>
  </uif-tablerow>
</uif-table>
```

**Table**, **tablerow** and **tablecell** directives denote respectively a table, table row and a table cell. **Tablerowcheck** renders the checkbox in the first column. A row can be marked as selected using the **selected** attribute.

Please note that currently Office UI Fabric doesn't offer any support for interactively selecting rows. I suggest that we first go for alignment with the Fabric and then start adding new capabilities.

**Comment by andrewconnell** [comment]
OK... so while we do want to stay with the spirit of fabric, we also want to keep in mind these are going to be components in applications. One of the main goals here is to ensure that these directives are not just "save me time from writing all the CSS classes that fabric needs" but also to make the developer more productive. To me, looking at the spec as is, I just see "so this just rewrites the HTML"... it might be ok for the first pass just to see something working, but not terribly useful.

You're right that fabric doesn't support interactively selecting rows (_that's debateable as I think it does from this codepen: http://codepen.io/andrewconnell/pen/RWGgmY_)... but fabric does not have any functionality in it... it is JUST CSS. That's where this project is playing a role. 

With that in mind...
- I see a few references to `uit-` not `uif-`… Need to clean those up in the spec.
- Do we need to use “table” in every cell & row? Why not `uif-row` `uif-cell` as those directives won’t be in any other structures.
- I see `selected` … This should be a Boolean property (_default to `false`_) on the row like `uif-selected` as it’s not a standard thing in HTML.
- Think like ASP.NET GridView... This needs bindable attributes for things like collections... ability to bind a collection of items and have it build the rows & columns for you... however you should also be able to pass in a template on how you want them implemented, so for the spec I think you'd want to include other scenarios like (_the attributes / elements need some work... just throwing it out there to start the discussion_):

``` html
<uif-table>
  <uif-row ng-repeat="var planet in solarsystem.planets"
      uif-isRowSelected="{{planet.isSelected}}">
    <uif-cell>..</uif-cell>
    <uif-cell>..</uif-cell>
    <uif-cell>..</uif-cell>
  </uif-row>
</uif-table>

// or
<uif-table uif-items="solarsystem.planets" 
    uif-rowselectable="true" 
    uif-selectedrow="{{thisCtrlr.selectedPlanet}}" />

// or
<uif-table uif-items="solarsystem.planets" 
    uif-rowselectable="true" 
    uif-selectedrow="{{thisCtrlr.selectedPlanet}}>
  <uif-rowTemplate>
    <uif-cell uif-isSortable="true">{{item.position}}</uif-cell>
    <uif-cell uif-isSortable="true">{{item.name}}</uif-cell>
  </uif-rowTemplate>
</uif-table>
```

While some of this stuff might not make the P1, let's think what the ideal goal would be and then scope it.

**Comment by waldekmastykarz** [comment]
In some scenario's the Fabric is more than CSS. If you for example take a look at Spinner or People Picker the interaction is already covered for by the Fabric. All we need to do is to fill the component with data. With that I wonder what the odds are that things such as sorting table or selecting rows will be provided as a part of the Fabric and we would be able to leverage it rather than building it ourselves.
- `uit` > `uif`: my bad, sorry, will fix it
- `uif-tablerow` vs. `uif-row`: wouldn't this shorter notation cause trouble if we wanted to implement responsive grid or is responsive grid not something we would include because it's only HTML?
- `uif-selected` to denote selected rows: good point. I personally prefer it over `uif-isRowSelected` as it's shorter and just as clear
- the templating part is confusing. Looking at ngMaterial there are two different approaches I've seen used in different components:

First, if you look at Chips (https://material.angularjs.org/latest/demo/chips) there is a model binding and a template (kind of ASP.NET repeater), which resembles your last suggestion. Then, some components such as List (https://material.angularjs.org/latest/demo/list) use ng-repeat as you showed in the first sample. Depending on which approach we choose there are different implications further down the road, such as specifying table headers.

From Fabric markup perspective table headers are no different than regular rows and are visually different using CSS. Using the `ng-repeat` construction we could easily define the headers by simply adding another row:

``` html
<uif-table>
  <!-- header -->
  <uif-row>
    <uif-cell uif-sortable="true">Planet name</uif-cell>
    <uif-cell uif-sortable="true">Distance from Earth</uif-cell>
    <uif-cell>...</uif-cell>
  </uif-row>
  <!-- planets -->
  <uif-row ng-repeat="var planet in solarsystem.planets"
      uif-selected="{{planet.isSelected}}">
    <uif-cell>..</uif-cell>
    <uif-cell>..</uif-cell>
    <uif-cell>..</uif-cell>
  </uif-row>
</uif-table>
```

In all other cases we would need a separate template for defining header templates:

``` html
<uif-table uif-items="solarsystem.planets" 
    uif-rowselectable="true" 
    uif-selectedrow="{{thisCtrlr.selectedPlanet}}">
  <uif-headerTemplate>
    <uif-cell>Position</uif-cell>
    <uif-cell uif-sortable="true">Name</uif-cell>
  </uif-headerTemplate>
  <uif-rowTemplate>
    <uif-cell>{{item.position}}</uif-cell>
    <uif-cell>{{item.name}}</uif-cell>
  </uif-rowTemplate>
</uif-table>
```

With regards to sorting columns: it should be only possible to apply sorting to the cells in the header row. In HTML these cells are marked up as TH whereas regular cells ar TD. We could achieve the same by introducing a separate directive for these cells that would support sorting:

``` html
<uif-table>
  <!-- header -->
  <uif-row>
    <uif-headercell uif-sortable="true">Planet name</uif-headercell>
    <uif-headercell uif-sortable="true">Distance from Earth</uif-headercell>
    <uif-headercell>...</uif-headercell>
  </uif-row>
  <!-- planets -->
  <uif-row ng-repeat="var planet in solarsystem.planets"
      uif-selected="{{planet.isSelected}}">
    <uif-cell>..</uif-cell>
    <uif-cell>..</uif-cell>
    <uif-cell>..</uif-cell>
  </uif-row>
</uif-table>
```

Do you know if there are any serious implications for choosing ng-repeat or ng-model with templates that might haunt us down the road?

**Comment by andrewconnell** [comment]
**RE: Fabric being more than CSS...**

Sorry but that's not accurate... actually Fabric **is just CSS**. I know this seems like splitting hairs, but this is a very important point for our library to understand. There are some components where they have created some _sample_ JavaScript; it is added just to show how the CSS can be used If you talk to the team, they are emphatic that the JS is not part of the library... it's provided as a sample. I went back and forth with the team a ton on this in the previews & post announcement saying they had to publish the JS because some components were almost useless without... they were firm that fabric is only CSS.

While there is some JS shown on some samples in their online demos, if you [look at what they've published](http://dev.office.com/fabric/getting-started), _only_ the CSS is provided in the CDN. If you want to use their JS, you have to go into the specific folder within the source of the library and pull it out manually. The JS they provide is done so using JQuery extensions and we are not going to take any dependencies on jQuery in the ngOfficeUiFabric... the only dependencies we are going to take are (1) Angular & (2) any library fabric requires, such as `pickadate.js` (that's the only one at this point). 

So as such, any selecting / sorting / interaction that we do will need to be written using plain JS & Angular... or using the jQueryLight that's embedded within Angular.

**RE: shorter table notation**

Honestly don't know... it warrants some time looking into Angular Material & UIBootstrap to see if they have any components that have a similar challenge.

As a developer, I know I'd prefer the shorter syntax and prefer to avoid the longer, repetitive things.

**RE: Templating vs. Repeaters**

Templates are hard... I'm not sure which is more popular in other frameworks (like Angular Material & UIBootstrap). If it makes sense to focus on repeaters then can do that... might make best sense for a P1 anyway.

**RE: Header Row**
Would be nice (and pretty sure you can figure this out) to have the directive figure out if you are on the first row so you can avoid having to use a different option for different cells... maybe a few mockups to see what _feels_ best?

``` html
<uif-table>
  <uif-row isHeader="true">
    <uif-cell>..</uif-cell>
  </uif-row>

  // or
  <uif-row>
    <uif-cell isHeader="true">..</uif-cell>
  </uif-row>

  // or
  <uif-row>
    <uif-headerCell>..</uif-cell>
  </uif-row>

  // or
  <uif-row>
    <uif-heading>..</uif-cell>
  </uif-row>

</uif-table>
```

**Comment by waldekmastykarz** [comment]
Fell for it again: you're right: Fabric is CSS only. We've discussed this before.

**RE: Shorter table notation**: let me check if I can find anything about it

**RE: Templating vs. Repeat**: :+1: on ng-repeat approach for p1

**RE: Header row**:
Just to double check: we want it to be obvious from the markup that the particular row is a header row rather than using some directive cleverness through DOM to figure it out in the code, right? Based on what we know now we need this information for the header cells rather than the whole header row.

How about?

``` html
<uif-table>
  <uif-row>
    <uif-rowselect></uif-rowselect>
    <uif-header>Position</uif-header>
    <uif-header uif-sortable="true">Name</uif-header>
  <uif-row>
  <uif-row ng-repeat="p in vm.planets" uif-selected="...">
    <uif-rowselect></uif-rowselect>
    <uif-cell>{{p.position}}</uif-cell>
    <uif-cell>{{p.name}}</uif-cell>
  </uif-row>
</uif-table>
```

**Comment by waldekmastykarz** [comment]
**RE: Shorter table notation**:
I've had a look at a couple of bootstrap and ngMaterial components but haven't found a single case of using the same directives for different purpose in different components. In all cases it's either a unique name or a name prefixed with the component (ie. `md-grid-title`): I assume this is to avoid name conflicts in the future.

Another thing I've noticed is that regularly custom attributes are set on directives but these attributes are not attribute directives, they are simply used to pass values to directives. For example of this you can look at the usage of the `md-direction` attribute (https://github.com/angular/material/search?utf8=✓&q=mdDirection&type=Code). It's a bit confusing at first to separate real attribute directives from attributes but it's a convenient way of passing parameters to directives making them configurable.

**Comment by andrewconnell** [comment]
You def don't have to create attribute directives for each thing... like you see, it's simply an easy way to pass values to & from the element directive & the way to go. If it's a custom attribute we are defining, prefix it with **uif-** but don't create a directive for it.

**Comment by waldekmastykarz** [comment]
Based on the latest findings, how about we proceed with the following:

``` html
<uif-table>
  <uif-table-row>
    <uif-table-rowselect></uif-table-rowselect>
    <uif-table-header>Position</uif-table-header>
    <uif-table-header uif-sortable="true">Name</uif-table-header>
  <uif-table-row>
  <uif-table-row ng-repeat="p in vm.planets" uif-selected="...">
    <uif-table-rowselect></uif-table-rowselect>
    <uif-table-cell>{{p.position}}</uif-table-cell>
    <uif-table-cell>{{p.name}}</uif-table-cell>
  </uif-table-row>
</uif-table>
```

**Comment by andrewconnell** [comment]
works for me
