### ISSUE TITLE
Create component: icon

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#40]
This isn't in Office UI Fabric, but would be used by multiple directives as well as outside the components. See issue #14 for reference.

**Spec**:

```
<uif-icon uif-type="plus" />
```

This would render out the HTML that uses the icon for a PLUS.

**Comment by waldekmastykarz** [comment]
Shouldn't the directive have set

``` js
public replace: boolean = true;
```

at https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/a4247e56f3bbab011877d48adaf7d8d664d0ac9a/src/components/icon/iconDirective.ts#L29? Currently if you look at the rendered DOM in the browser the `<i>` element is wrapped with the `<uif-icon>` element from the directive. Shouldn't the output be simply the template HTML without it being wrapped in the directive?

**Comment by s-KaiNet** [comment]
That's interesting, because in official docs `replace` is [deprecated](https://docs.angularjs.org/api/ng/service/$compile#-replace-deprecated-will-be-removed-in-next-major-release-i-e-v2-0-) since angular 1.3. But there are still many [debates](http://stackoverflow.com/questions/24194972/why-is-replace-deprecated-in-angularjs) why it's deprecated and some folks from angular team reported that this [won't be deprecated](https://github.com/angular/angular.js/commit/eec6394a342fb92fba5270eee11c83f1d895e9fb#commitcomment-8124407).

**Comment by waldekmastykarz** [comment]
Another thing that's curious is that ngMaterial directives use replace: true too, eg. https://github.com/angular/material/blob/8ef798f0fe242c555ef7c11fa0abe762fb218a02/src/components/button/button.js#L68

**Comment by andrewconnell** [comment]
I saw the same debate going back and forth... for now I left it as is because it's working just fine... but open to changing it later.

**Comment by waldekmastykarz** [comment]
:+1:
