### ISSUE TITLE
Dropdown jumps to the upper right corner if screen is too small

### ISSUE THREAD

**Issue by asigmund** [ngOfficeUIFabric/ng-officeuifabric#414]
The dropdown jumps to the upper right corner if the screen gets to small. You can reproduse the issue with the demo example. See the picture below.

![image](https://cloud.githubusercontent.com/assets/4354697/19043459/8889b1e4-8990-11e6-8b10-bf69a47f8bba.png)

**Comment by andikrueger** [comment]
This is an OfficeUiFabric Issue: https://github.com/OfficeDev/office-ui-fabric-core/issues/552

**Comment by andrewconnell** [comment]
As @andikrueger says, unfortunately, this isn't something we can fix. It's a CSS bug from Office UI Fabric. They fixed it in v3, but they didn't go back and fix it in v2.6.2. Since v3 is really a fork with a TON of other CSS changes to support MDL2, and because we get the CSS from their library, we can't just upgrade out dependency to their latest version in this iteration. We aren't currently shipping a CSS file, just the JS library.

I've [left a comment to see if they'll consider it](https://github.com/OfficeDev/office-ui-fabric-core/issues/552#issuecomment-266396672), but I wouldn't expect they will address it.

If you want to address this for your implementation, suggest adding your own CSS to patch their CSS after loading their CSS file. Here's the commit that fixed it: https://github.com/OfficeDev/office-ui-fabric-core/pull/602/commits/3bf4cd96d0205f38bfe61d54374c0945e91e9ad9

**Comment by andrewconnell** [comment]
Whoa... stop the presses! 

Looks like the Fabric guys are going to fix this for us. Reopening this issue to track: https://github.com/OfficeDev/office-ui-fabric-js/issues/261

Once they close it I'll close this issue out. Still listed as `wontfix` because we aren't the ones fixing though.

**Comment by andrewconnell** [comment]
Closing the loop on this... this has been fixed upstream in Fabric 2.6.3. Will update our dependency to 2.6.3 once it reaches the CDN.

See this for reference: https://github.com/OfficeDev/office-ui-fabric-js/issues/261#issuecomment-280957153
