### ISSUE TITLE
[DatePicker] - value of Reference button is not updated

### ISSUE THREAD

**Issue by jskvoll** [ngOfficeUIFabric/ng-officeuifabric#486]
Issue found by my team member.

Reproduces: 
http://ngofficeuifabric.com/demos/uifDatepicker/

### Expected Behavior
Value of Reference button contains current month and current year 

### Actual Behavior

Value of Reference button contains year you previously selected
### Steps to Reproduce Behavior
1.Open Date picker
2.Click Reference button with month and year label 
3.Click Reference button with year label
4.Select any other year
5.Click “Go to today” button
6.Open Date picker
7. Move to years again

http://i.imgur.com/rKchKVn.gifv

**Comment by andrewconnell** [comment]
Unfortunately, this bug is coming from the [pickadate.js](https://github.com/amsul/pickadate.js) library which we take a dependency on because that's what Office UI Fabric v2.6.* takes a dependency on... just as I explained in #493. Therefore this bug needs to be addressed in that library as it's not something we can fix in this project.
