### ISSUE TITLE
uif-choicefield: throwing lots errors on dirty setting

### ISSUE THREAD

**Issue by andrewconnell** [ngOfficeUIFabric/ng-officeuifabric#500]
### Expected Behavior
No errors thrown

### Actual Behavior
Lots of errors thrown

### Steps to Reproduce Behavior
Go to live demo http://ngofficeuifabric.com/demos/uifChoicefield, open dev tools & try last demo.

**Comment by architshukla** [comment]
This seems to be happening due to a missing check for the absence of `ng-model`  [here](https://github.com/ngOfficeUIFabric/ng-officeuifabric/blob/master/src/components/choicefield/choicefieldDirective.ts#L233). Making the change locally fixes the issue for the third and the last examples.

I have two questions though:
1. In the last example, it's possible to select multiple radio buttons. Is this expected?
![image](https://user-images.githubusercontent.com/4814585/27154461-bf2e789c-5172-11e7-826a-4dfd5b656089.png)

2. The third (checkbox) example is currently throwing errors as well due to the same reason. Even though the errors go away after the fix, the `ng-model` on the checkbox doesn't seem to be working:
![image](https://user-images.githubusercontent.com/4814585/27155981-b84e78c8-5178-11e7-8f40-7446e2cde8b4.png)
The value of `selectedCheckbox` isn't being set in either state. Am I missing something?

**Comment by andrewconnell** [comment]
Thanks for the suggested fix... want to submit a PR and help out?

For the other thing you mention, seems a dupe of #482
